services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

  client-api:
    build: ./client-api
    ports:
      - "8010:8010"
    networks:
      - monitoring

  front-deadend:
    build: ./frontend-m
    ports:
      - "3001:3001"
    networks:
      - monitoring

  build-server:
    build: ./build-server-api
    ports:
      - "8011:8011"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage: