pipeline {
    agent any

    environment {
        IMAGE_NAME = "build-server-api"
        IMAGE_TAG = "latest"
    }

    triggers {
        // Polling the deployment branch for changes
        pollSCM('H/5 * * * *') //  every 5 minutes 
    }

    stages {
        stage('Checkout Code') {
            when {
                branch 'deployment' // Only run if on deployment branch
            }
            steps {
                git branch: 'deployment', url: 'https://github.com/Alostwayfarer/DNS-Capstone/tree/main/build-server%20api'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh "docker run -d -p 3000:3000 ${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
    }

    post {
        always {
            sh 'docker system prune -f'
        }
    }
}