global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'client-api'
    static_configs:
      - targets: ['client-api:8010']

  - job_name: 'frontend'
    static_configs:
      - targets: ['localhost:3001']

  - job_name: 'build-server'
    static_configs:
      - targets: ['localhost:8080']